apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pvc-demo
  namespace: openshift-gitops
spec:
  destination:
    namespace: pvc-demo
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: pvc-demo/overlays/demo
    repoURL: https://github.com/meidlinger/pvc-demo
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
